// <auto-generated />
namespace MarathaBusinessApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class thirddatanew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(thirddatanew));
        
        string IMigrationMetadata.Id
        {
            get { return "201812191346551_thirddatanew"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
